INSERT INTO T_PAGE_PROPERTY_VALUE (F_PAGE_PROPERTY_ID, F_VALUE, F_LANG_ID) VALUES (1, 'Редактор контента', 3);
INSERT INTO T_PAGE_PROPERTY_VALUE (F_PAGE_PROPERTY_ID, F_VALUE, F_LANG_ID) VALUES (2, 'Изображение', 3);
INSERT INTO T_PAGE_PROPERTY_VALUE (F_PAGE_PROPERTY_ID, F_VALUE, F_LANG_ID) VALUES (3, '500', 3);
INSERT INTO T_PAGE_PROPERTY_VALUE (F_PAGE_PROPERTY_ID, F_VALUE, F_LANG_ID) VALUES (4, '300', 3);
INSERT INTO T_PAGE_PROPERTY_VALUE (F_PAGE_PROPERTY_ID, F_VALUE, F_LANG_ID) VALUES (5, 'Редактор контента', 3);
INSERT INTO T_PAGE_PROPERTY_VALUE (F_PAGE_PROPERTY_ID, F_VALUE, F_LANG_ID) VALUES (6, 'Документ', 3);
INSERT INTO T_PAGE_PROPERTY_VALUE (F_PAGE_PROPERTY_ID, F_VALUE, F_LANG_ID) VALUES (7, '600', 3);
INSERT INTO T_PAGE_PROPERTY_VALUE (F_PAGE_PROPERTY_ID, F_VALUE, F_LANG_ID) VALUES (8, '200', 3);

INSERT INTO T_PAGE_PROPERTY_VALUE (F_PAGE_PROPERTY_ID, F_VALUE, F_LANG_ID) VALUES (9, 'XML файл', 3);
INSERT INTO T_PAGE_PROPERTY_VALUE (F_PAGE_PROPERTY_ID, F_VALUE, F_LANG_ID) VALUES (10, 'Текст', 3);
INSERT INTO T_PAGE_PROPERTY_VALUE (F_PAGE_PROPERTY_ID, F_VALUE, F_LANG_ID) VALUES (11, '150', 3);
INSERT INTO T_PAGE_PROPERTY_VALUE (F_PAGE_PROPERTY_ID, F_VALUE, F_LANG_ID) VALUES (12, '150', 3);
INSERT INTO T_PAGE_PROPERTY_VALUE (F_PAGE_PROPERTY_ID, F_VALUE, F_LANG_ID) VALUES (13, 'XML файл', 3);
INSERT INTO T_PAGE_PROPERTY_VALUE (F_PAGE_PROPERTY_ID, F_VALUE, F_LANG_ID) VALUES (14, 'График', 3);
INSERT INTO T_PAGE_PROPERTY_VALUE (F_PAGE_PROPERTY_ID, F_VALUE, F_LANG_ID) VALUES (15, '80', 3);
INSERT INTO T_PAGE_PROPERTY_VALUE (F_PAGE_PROPERTY_ID, F_VALUE, F_LANG_ID) VALUES (16, '120', 3);

COMMIT;